In [1]:
import numpy as np

In [33]:
a = np.array([1, 2, 3,4,5,0.5,0]) 

print('Data Type of Array: ', a.dtype)


Data Type of Array:  float64


In [20]:
b = np.array([3,3,4,3])
print('Data Type:', b.dtype)
print(a.dtype)

Data Type: int32
int32


In [12]:
c = np.array([1, 2, 3,4,5], dtype='f')
print(c.dtype)


float32


In [15]:
d = np.array([4,5,4,3,5], dtype='f8')
print(d.dtype)

float64


In [21]:
e = np.array([1.1,  2.5,  0.6, 4.7, 5.3]) 


In [35]:
e=e.astype("i")
a=a.astype(bool)


In [36]:
# print(e)
print(a)

[ True  True  True  True  True  True False]


In [42]:
a = np.array( [1.1,  2.5,  0.6, 4.7, 5.3] ) 

print('Base of Array-A: ', a.base )


Base of Array-A:  None


In [47]:
b=a.copy()
b[0]=10
print('Values of Array -A ')

print(b)
print(a)
print('Base of Array-B: ', a.base )


Values of Array -A 
[10.   2.5  0.6  4.7  5.3]
[1.1 2.5 0.6 4.7 5.3]
Base of Array-B:  None


In [52]:
a = np.array( [1.1,  2.5,  0.6, 4.7, 5.3] ) 
c=a.view()
c[0]=10;
print(c)
print(a)
print('Base of Array-C: ', c.base )


[10.   2.5  0.6  4.7  5.3]
[10.   2.5  0.6  4.7  5.3]
Base of Array-C:  [10.   2.5  0.6  4.7  5.3]


In [53]:
ar= np.array([1,2,3,4,5,6,7,8])

In [55]:
print(ar.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [56]:
print(ar.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [59]:
print(ar.reshape(8,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [66]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

for row in a:
  for col in row:
    print(col)


1
2
3
4
5
6
7
8


In [ ]:
for col in np.nditer(a):
    print(col)


1
2
3
4
5
6
7
8


In [71]:
print(a)
for id, x in np.ndenumerate(a):
    print(id, x)

[[1 2 3 4]
 [5 6 7 8]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [72]:
x = np.array([ [1,5,2,5], [5,7,6,5] ]) 


In [78]:
abc=np.where(x>5)
print(abc)


(array([1, 1], dtype=int64), array([1, 2], dtype=int64))
