In [1]:
import numpy as np

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

Simple Nested Loop – Print Each Value in row

In [ ]:
print('Simple Loop - Print each value in row')

for row in a:
    for col in row:
        print(col)

Simple Loop - Print each value
1
2
3
4
5
6
7
8


np.nditer() – Print Each Value in row with special iterator

In [4]:

for val in np.nditer(a):
    print(val)

1
2
3
4
5
6
7
8


In [5]:
for id, val in np.ndenumerate(a):
    print(id, val)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


Sorting Array

In [19]:
b = np.array([1,4,3,2,5,8,7,6])
print(b.shape)

print(np.sort(b))

(8,)
[1 2 3 4 5 6 7 8]


Searching in Array

In [10]:
print("Search the Even Numbers")
x = np.where(b % 2 == 0)
print(x)

Search the Even Numbers
(array([1, 3, 5, 7], dtype=int64),)


Important: np.where() value nahi, index return karta hai.

In [11]:
print("Search the Even Numbers")
abc = (b % 2 == 0)
print(abc)

Search the Even Numbers
[False  True False  True False  True False  True]


In [ ]:
ind = (b % 2 == 0)
arr = b[ind]
print(arr)


[4 2 8 6]


2D Array


In [20]:
t = np.array([
[10,20,30,'red'],
[21,31,41,'green'],
[50,60,70,'brown'],
[89,97,11,'green']
])

row = np.where(t == 'green')
print(row)

# rs = t[row]
# print(rs)

(array([1, 3], dtype=int64), array([3, 3], dtype=int64))
