Install Numpy


In [1]:
import numpy as np

In [4]:
print('Numpy Version : ', np.__version__)


Numpy Version :  2.2.6


Create Array with Numpy 

In [ ]:
arr1 = np.array(5)
print(arr1)

1


In [8]:
arr2 = np.array([1,2,3,4,5])
print(arr2)

[1 2 3 4 5]


Note: There is no commas in numpy array

Check Data types--

In [12]:
print('Array 1 Data Type : ', type(arr1))
print('Array 2 Data Type : ', type(arr2))

Array 1 Data Type :  <class 'numpy.ndarray'>
Array 2 Data Type :  <class 'numpy.ndarray'>


np.array() - Always create ndarray

Python list is not equal to numpy array

In [14]:
arr3 = np.array([[1,2,3], [4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


Check Dimensions, Shape and Size...

In [15]:
print('Array Dim :', arr3.ndim)
print('Array Shape :', arr3.shape)
print('Array Size :', arr3.size)

Array Dim : 2
Array Shape : (2, 3)
Array Size : 6


3D Array

In [16]:
arr4 = np.array(
   [
      [ [1,2,3], [4,5,6] ],
      [ [1,2,3], [4,5,6] ]
   ]
)

Access the Elements.. 1D Array

In [ ]:
print( arr2[2])
print( arr2[-3])


First Element :  3
First Row :  3


Access the Elements of 2D Array

In [24]:
arr5 = np.array([
 [1,2,3], 
 [4,5,6] 
])

In [25]:
print( arr5[0,1])


2


In [27]:
print( arr3[-2,-2])

2


In [26]:
print( arr5[0,-1])


3


In [ ]:
print( arr3[0,4])

Slicing for Accessing 1D Array Elements


In [32]:
a = np.array([1, 2, 3, 4])


array[start : stop : step]


In [39]:
print(a[-3:-1])

[2 3]


In [47]:
print( a[0:3:1])

[1 2 3]


In [49]:
print(a[:])

[1 2 3 4]


In [48]:
print(a[::-1])

[4 3 2 1]


Slicing for Accessing 2D Array Elements


Rule:  a[row_slice , column_slice]

In [53]:
a2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10,11,12]
])

In [54]:
print( a2[0,1])

2


In [57]:
print(a2[1:3, 0:2])

[[4 5]
 [7 8]]


Creating Some diff type of matrices

In [63]:
x = np.empty([3,2], dtype=int)
print(x)

[[3403141798744321641       2034197026208]
 [                  0                   0]
 [                  0                   0]]


In [64]:
print(type(x))

<class 'numpy.ndarray'>


In [66]:
y = np.ones([2,2])
print(y)

[[1. 1.]
 [1. 1.]]


In [67]:
z = np.ones([3,2], dtype=int) 
print(z)

[[1 1]
 [1 1]
 [1 1]]
