In [1]:
import numpy as np

In [6]:
a = np.array([1.0,5.2,3.6,2.2])
b=a.copy()
b[0]=10
print(b)
print(a)
print(b.base)


[10.   5.2  3.6  2.2]
[1.  5.2 3.6 2.2]
None


In [12]:
c= np.array([4,5,6,8,5,6])
print(c)
c= c.reshape(2,3)
print(c)
print(c.shape)


[4 5 6 8 5 6]
[[4 5 6]
 [8 5 6]]
(2, 3)


In [13]:
for x in np.nditer(c) :
    print(x)


4
5
6
8
5
6


In [14]:
for x in np.ndenumerate(c) :
    print(x)


((0, 0), np.int64(4))
((0, 1), np.int64(5))
((0, 2), np.int64(6))
((1, 0), np.int64(8))
((1, 1), np.int64(5))
((1, 2), np.int64(6))
